// <auto-generated />
using System;
using CardTrader3000.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CardTrader3000.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261004042256_JsonImport")]
    partial class JsonImport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("CardTrader3000.Data.Entities.ImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bucket1Count")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bucket2Count")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedCardCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FinalValueFeeRate")
                        .HasColumnType("REAL");

                    b.Property<double>("FixedOrderFee")
                        .HasColumnType("REAL");

                    b.Property<int>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MergedCardCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("NewCardCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<double>("OverallNetMarginPercent")
                        .HasColumnType("REAL");

                    b.Property<string>("RawResponseJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<double>("StandardEnvelopeRate")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCardsEvaluated")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalEbayFees")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalGrossRevenue")
                        .HasColumnType("REAL");

                    b.Property<int>("TotalInputLines")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalMaxNetReturn")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalPostage")
                        .HasColumnType("REAL");

                    b.Property<int>("UnpricedCardCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc");

                    b.ToTable("ImportBatches");
                });

            modelBuilder.Entity("CardTrader3000.Data.Entities.ImportBatchItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bucket")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardSet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CreatedNewCard")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<double?>("EstimatedListPrice")
                        .HasColumnType("REAL");

                    b.Property<int>("ImportBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InventoryCardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineNumber")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaxNetReturn")
                        .HasColumnType("REAL");

                    b.Property<string>("Parallel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PricingProvided")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProvidedDataJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityAdded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SgcCandidate")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SkipPricing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("InventoryCardId");

                    b.ToTable("ImportBatchItems");
                });

            modelBuilder.Entity("CardTrader3000.Data.Entities.InventoryCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardSet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EbayDescription")
                        .HasColumnType("TEXT");

                    b.Property<double>("EbayFee")
                        .HasColumnType("REAL");

                    b.Property<string>("EbayTitle")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<double>("EstimatedListPrice")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsRookie")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastPricedUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxNetReturn")
                        .HasColumnType("REAL");

                    b.Property<double>("NetMarginPercent")
                        .HasColumnType("REAL");

                    b.Property<string>("NormalizedKey")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("TEXT");

                    b.Property<string>("Parallel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("PostageCost")
                        .HasColumnType("REAL");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SalesStrategy")
                        .HasColumnType("TEXT");

                    b.Property<string>("SgcCandidate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalFees")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Bucket");

                    b.HasIndex("CardSet");

                    b.HasIndex("NormalizedKey")
                        .IsUnique();

                    b.HasIndex("PlayerName");

                    b.HasIndex("SgcCandidate");

                    b.HasIndex("Status");

                    b.ToTable("InventoryCards");
                });

            modelBuilder.Entity("CardTrader3000.Data.Entities.ImportBatchItem", b =>
                {
                    b.HasOne("CardTrader3000.Data.Entities.ImportBatch", "ImportBatch")
                        .WithMany("Items")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CardTrader3000.Data.Entities.InventoryCard", "InventoryCard")
                        .WithMany("ImportItems")
                        .HasForeignKey("InventoryCardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ImportBatch");

                    b.Navigation("InventoryCard");
                });

            modelBuilder.Entity("CardTrader3000.Data.Entities.ImportBatch", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CardTrader3000.Data.Entities.InventoryCard", b =>
                {
                    b.Navigation("ImportItems");
                });
#pragma warning restore 612, 618
        }
    }
}
